### ISSUE TITLE
Currency on right

### ISSUE THREAD

**Issue by dominik-wbz** [Invoiced/invoice-generator-api#11]
Is there a way to display the currency on right for currencies such as "czk". Eg. "100 Kč" insted of "Kč 100".

Thanks

**Comment by christopheblin** [comment]
This is also true for euros

As an additional localization issue, the comma is not the separator for thousands and the dot is not separator from decimal, you should add a locale parameter to deal with that

**Comment by jaredtking** [comment]
Hi there! This should be fixed now if you supply locale in the Accept-Language header. Money amounts are formatted according to locale provided using the ICU library. The default is en-US. Please reopen if you continue to face issues.

Here is more information on how to do this: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language

Thank you for the feedback!
