### ISSUE TITLE
invoice_number_title ignored?

### ISSUE THREAD

**Issue by invoicer-it** [Invoiced/invoice-generator-api#15]
The parameter invoice_number_title seemed to be ignored, instead I always get "#".
Is this a bug?

Thanks!

**Comment by jaredtking** [comment]
The invoice number title is no longer a parameter and should be removed from the documentation or else implemented. Sorry for the confusion!

**Comment by jaredtking** [comment]
The `invoice_number_title` property is now available. It defaults to `#` if a value is not provided in API calls. Thanks for the feedback!
