### ISSUE TITLE
decimal places style

### ISSUE THREAD

**Issue by invoicer-it** [Invoiced/invoice-generator-api#16]
Can we have an enhancement to choose which style the decimal places have? 
The "apex" style is rather fancy and would be nice to have a regular plain one.

Thanks!

**Comment by jaredtking** [comment]
Great idea! We will add this one to the wish list as an optional setting.

**Comment by mateuszjanusz** [comment]
Hey, I'd also like the option to use the regular decimal places. Do you consider implementing it in the near future?

Thanks

**Comment by jaredtking** [comment]
We've just released an update that normalizes the money formatting. It uses a more standard format and decimals are consistently shown (previously they could be hidden on round amounts). Thank you for the feedback!
