### ISSUE TITLE
Have question about fields header

### ISSUE THREAD

**Issue by Aikoku** [Invoiced/invoice-generator-api#17]
Hello, can you please help me to make other header for fields.
I have this JSON:
`{
  "from": "Name",
  "to": "Test\nUSA",
  "number": 1,
  "items": [
    {
    "name": "Starter plan",    
    "quantity": 2,
    "unit_cost": 5
    },{
    "name": "Second Starter plan",    
    "quantity": 5,
    "unit_cost": 15
    }
  ],
  "notes": "Thanks for your business!"
}`

How to rename Quantity to hours or unit_cost header(Rate) to Something else?

**Comment by RamanObaid** [comment]
See https://github.com/Invoiced/invoice-generator-api
Have a look at the "Invoice Template" section
You can send a JSON like this:-
{
unit_cost_header: "your custom header"//change Rate header,
quantity_header: "your custom header. e.g Units"//change Quantity header

 "from": "Name", "to": "Test\nUSA", "number": 1, "items": [ { "name": "Starter plan", "quantity": 2, "unit_cost": 5 },{ "name": "Second Starter plan", "quantity": 5, "unit_cost": 15 } ], "notes": "Thanks for your business!" }

**Comment by jaredtking** [comment]
As RamanObaid mentioned you can see the API reference for the fields that will allow you to change the wording on the template, i.e. `from_title`.

**Comment by Aikoku** [comment]
Thank you, that's help.
