### ISSUE TITLE
INR symbol not generated

### ISSUE THREAD

**Issue by Gauravshah** [Invoiced/invoice-generator-api#2]
`₹ ` symbol does not get printed in to PDF.

![screen shot 2015-04-12 at 3 37 19 am](https://cloud.githubusercontent.com/assets/620559/7105265/3f12b616-e0c5-11e4-9d8b-362e075ef0b1.png)
![screen shot 2015-04-12 at 3 35 47 am](https://cloud.githubusercontent.com/assets/620559/7105266/3f1d5a6c-e0c5-11e4-887c-588501534dd5.png)

**Comment by jaredtking** [comment]
We learned that adoption of the `₹` symbol is currently not widespread enough causing it to sometimes be missing from the resulting PDF. We've reverted to using `Rs` as the INR currency symbol until there's more adoption for the new `₹` symbol.
