### ISSUE TITLE
Currency symbol for Egyptian Pound (EGP) is incorrect

### ISSUE THREAD

**Issue by fadi-wissa** [Invoiced/invoice-generator-api#20]
For Egyptian pound (EGP) the used symbol is the British Pound symbol (£) while it should be E£ (preceded with an "E") - otherwise it's misleading.

**Comment by jaredtking** [comment]
I agree with you on this change. Thanks for the feedback! Once we have an update we will notify you here.

**Comment by jaredtking** [comment]
This should be fixed now. Thank you!
