### ISSUE TITLE
Your documentation is to difficult too understand for changing currency

### ISSUE THREAD

**Issue by pecoraladi** [Invoiced/invoice-generator-api#23]
Please post a working example to your README.md which shows how the currency symbol is changed.

**Comment by jaredtking** [comment]
You would pass in the 3-digit ISO-4217 currency code using the `currency` parameter as [documented here](https://github.com/Invoiced/invoice-generator-api#invoice-options). The currency symbol will be a function of the currency code you provide. For example, if you are using `USD` as the currency code then the currency symbol will be `$`.
