### ISSUE TITLE
Amount column custom value allowed?

### ISSUE THREAD

**Issue by kshkrao3** [Invoiced/invoice-generator-api#24]
This is rather a question. 

The last column `Amount` value is auto-generated with calculation `quantity *  rate` or we can specify custom values? I would be adding a certain extra amount to the amount field for each product. 

I tried to mention `'amount': calculatedAmount`  but it did not work. Could you please clarify/help?

**Comment by kshkrao3** [comment]
@jaredtking Any help on this?

**Comment by jaredtking** [comment]
There's actually a simple solution for this! You can set the quantity to 1 and enter your calculated amount into the rate. The amount will then be the rate that you've entered.

**Comment by kshkrao3** [comment]
@jaredtking Yea, that would have been helpful but the scenario we have here will not let us do so.  Each item can have an optional item included and that extra cost will be dependant on this, So in the rate, we would like to retain the same to display exact rate of the item. Any other way is this possible?
