### ISSUE TITLE
Rounding of Final Amount

### ISSUE THREAD

**Issue by sankalp179** [Invoiced/invoice-generator-api#25]
Thanks for the wonderful API.
I have created the following invoice using the API.
![image](https://user-images.githubusercontent.com/8420318/37908190-12baafb6-3125-11e8-9b31-b98814432a82.png)

The Total Amount didnt get rounded off. Because of which -0.01 was shown as Balance Due.
Is there a way to fix it?

**Comment by jaredtking** [comment]
This should be fixed now. Thank you for the feedback!
