### ISSUE TITLE
Decimal separator

### ISSUE THREAD

**Issue by dabster2000** [Invoiced/invoice-generator-api#28]
It would be great if we could choose which decimal separator and thousands separator are used, either decimal point or decimal comma. Many countries reverse the use of decimal comma and point.

**Comment by possybility** [comment]
hitting the same issue when using EUR.

**Comment by jaredtking** [comment]
This is now possible if you set the Accept-Language header to the locale where your customer is located. The API will then format money amounts according to the locale you provide using the ICU library.

For example, the locale in the Accept-Language header could be de-CH, en-US, or any combination of language + country. The default locale is en-US.

We currently do not use the language component in the locale just yet so it would still be advised to explicitly provide the invoice template labels if you are presenting invoices in a different language than English.

Thanks for the feedback!
