### ISSUE TITLE
Currency Symbols

### ISSUE THREAD

**Issue by austinejei** [Invoiced/invoice-generator-api#3]
Hi,

Excellent work on the API.

However, i don't see the currency symbol for GHS displayed when i generate an invoice. According to https://en.wikipedia.org/wiki/ISO_4217, this is an ISO-compliant currency symbol.

Kindly review your API.

Waiting for feedback.

**Comment by jaredtking** [comment]
Hi there, thanks for reporting this! We've added GHS as a currency option.

**Comment by austinejei** [comment]
Thanks. Really appreciate it.
