### ISSUE TITLE
Remove Quantity

### ISSUE THREAD

**Issue by WillPwn4Food** [Invoiced/invoice-generator-api#30]
I'm not sure how to Remove the Quantity header, I've tried setting it to a blank string or a single space, but the bar will show a missing row of pixels on the top and bottom instead of just having no text. Is there something I'm missing or is this actually a bug?

**Comment by jaredtking** [comment]
Unfortunately removing the quantity column is not something we support.

**Comment by WillPwn4Food** [comment]
Ok, thanks for letting me know. It seems like the totals/subtotals work based on things having a quantity, just wasn't sure if I could hide every item saying quantity 1.

**Comment by jaredtking** [comment]
It's a great suggestion. Just not something we support today. We'll add this one to the wish list.
