### ISSUE TITLE
Add support Thai language

### ISSUE THREAD

**Issue by krittin-58** [Invoiced/invoice-generator-api#34]
I would to help translator this my language.

Thank.

**Comment by jaredtking** [comment]
We're happy to accept any new translations. If you could kindly create a Thai translation file using [this file](https://gist.github.com/jaredtking/0bc08af92efef5f7fcd39c36317277bd) as a template then we'll add it to invoice-generator.com.

**Comment by krittin-58** [comment]
I already translated a Thai language [this file](https://gist.github.com/krittin-58/69c05db91973a8db416323f6d8d34272). I hoped this will be useful.

Thank.

**Comment by jaredtking** [comment]
This is now live! Below is an example cURL call. Thank you for your contribution!

curl https://invoice-generator.com \
  -H "Accept-Language: th-TH" \
  -d from="Invoiced, Inc." \
  -d to="Acme Corp." \
  -d logo="https://invoiced.com/img/logo-invoice.png" \
  -d number=1 \
  -d currency=thb \
  -d date="Feb 9, 2015" \
  -d due_date="Feb 16, 2015" \
  -d items[0][name]="Starter plan monthly" \
  -d items[0][quantity]=1 \
  -d items[0][unit_cost]=99 \
> invoice.pdf
