### ISSUE TITLE
images for line items

### ISSUE THREAD

**Issue by gingerlime** [Invoiced/invoice-generator-api#4]
Invoice-generator looks great! such a neat idea and well executed.

Any chance of adding thumbnail images for each line item?

**Comment by jaredtking** [comment]
Thanks for the feedback! We don't have any plans to add thumbnail images right now, but I'm curious what is the use case for this?

**Comment by gingerlime** [comment]
Looking at generating invoices for online shop items, and each item should have a little thumbnail of the product.

**Comment by jaredtking** [comment]
Do you have an example of what this should look like that you can share
here?

On Nov 11, 2015, at 4:03 PM, gingerlime <notifications@github.com> wrote:

Looking at generating invoices for online shop items, and each item should
have a little thumbnail of the product.

—
Reply to this email directly or view it on GitHub
<https://github.com/Invoiced/invoice-generator-api/issues/4#issuecomment-155923755>
.

**Comment by gingerlime** [comment]
here's a couple of examples. One from amazon.de, the other one from another online shop, both in German, but you should get the picture (no pun intended)

![screenshot - 121115 - 09 23 36](https://cloud.githubusercontent.com/assets/524274/11113718/620e2206-891f-11e5-978b-bc4edfda3067.png)

![screenshot - 121115 - 09 24 45](https://cloud.githubusercontent.com/assets/524274/11113723/6735ec96-891f-11e5-9bd4-d42791d6a92d.png)

**Comment by jaredtking** [comment]
When you view orders on Amazon then you see the product images, however, if you download the invoice those images are not present on the actual invoice. This is not something we plan to implement so I will be closing the issue. We will keep it in mind though when planning out new features. Thanks!

**Comment by gingerlime** [comment]
Yeah I can imagine this being pretty niche feature, but I thought I should ask or suggest. Thanks for considering this.
