### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by turnono** [Invoiced/invoice-generator-api#41]
I am unable to call https://invoice-generator.com in node.js.
the error is CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by abhinaypandey02** [comment]
did you find a fix

**Comment by turnono** [comment]
It was actually a problem with my code not with this api. I was using it in a firebase function.

**Comment by abhinaypandey02** [comment]
I am trying to use it in my webcode, I want something like when the user clicks a button it requests the api and get the pdf invoice. But it shows cors error. Anyways is it working for firebase function? I will set it up

**Comment by turnono** [comment]
here is an example of how i used it, using the npm package: https://www.npmjs.com/package/node-libcurl

`export const generateInvoice = () => {
  const invoice = {
      logo: "http://invoiced.com/img/logo-invoice.png",
      from: "Invoiced\n701 Brazos St\nAustin, TX 78748",
      to: "Johnny Appleseed",
      currency: "usd",
      number: "INV-0001",
      payment_terms: "Auto-Billed - Do Not Pay",
      items: [
          {
              name: "Subscription to Starter",
              quantity: 1,
              unit_cost: 50,
          },
      ],
      fields: {
          tax: "%",
      },
      tax: 5,
      notes: "Thanks for being an awesome customer!",
      terms: "No need to submit payment. You will be auto-billed for this invoice.",

  };

  const postData = JSON.stringify(invoice);

  return curly.post("https://invoice-generator.com", {
    postFields: postData,
    httpHeader: [
      "Content-Type: application/json",
      "Accept: application/json",
      `Content-Length: ${Buffer.byteLength(postData)}`,
    ],
  });
};`

**Comment by addykoder** [comment]
Is there any other work around for that?

**Comment by jaredtking** [comment]
You need to make the request from a server instead of from a browser and it should work. The API does not support AJAX calls from a browser at this time.

**Comment by addykoder** [comment]
Yeah I was trying to download an invoice on a button click in the front-end
itself but send like this API isn't suitable for that.
