### ISSUE TITLE
Support for locale nl-NL and/or nl-BE

### ISSUE THREAD

**Issue by Nxtra** [Invoiced/invoice-generator-api#42]
Dear,

Can we also add support for the locales nl-NL and nl-BE?
If you can provide me the file with placeholder I'd be happy to add the translations in Dutch.

Cheers

**Comment by Nxtra** [comment]
Any feedback on the ability to support this. We're looking to use the API in one of our solutions but it would require a Dutch translation

**Comment by jaredtking** [comment]
It's not currently supported I'm afraid, but you can supply your own translation using these fields: https://github.com/Invoiced/invoice-generator-api#invoice-template

**Comment by Nxtra** [comment]
> It's not currently supported I'm afraid, but you can supply your own translation using these fields: https://github.com/Invoiced/invoice-generator-api#invoice-template

Right, good tip. I'll try that!
