### ISSUE TITLE
Unable to use with java code

### ISSUE THREAD

**Issue by nikunj0123** [Invoiced/invoice-generator-api#6]
I am trying to use https://invoice-generator.com with java code. It is executing successfully but no invoice is getting generated. Can someone please help?

**Comment by jaredtking** [comment]
Would you mind sharing your code please?

**Comment by nikunj0123** [comment]
OkHttpClient client = new OkHttpClient();

MediaType mediaType = MediaType.parse("application/json");
RequestBody body = RequestBody.create(mediaType, "{\"from\":\"Invoiced, Inc.\",\"to\":\"Parag\",\"logo\":\"https://invoiced.com/img/logo-invoice.png\",\"number\":1,\"items\":[{\"name\":\"Starter plan\",\"quantity\":1,\"unit_cost\":99}],\"notes\":\"Thanks for your business!\", \"currency\": \"INR\"}");
Request request = new Request.Builder()
  .url("https://invoice-generator.com/")
  .post(body)
  .addHeader("content-type", "application/json")
  .addHeader("cache-control", "no-cache")
  .build();

Response response = client.newCall(request).execute();

**Comment by jaredtking** [comment]
Could you try running this code with the URL set to `http://requestb.in/1nrrnio1`? It would help inspect what's actually being sent over the wire. Thanks!

**Comment by nikunj0123** [comment]
Done.

**Comment by nikunj0123** [comment]
How to save response in PDF will also help me.

**Comment by nikunj0123** [comment]
No. I am not getting any error. But I want to create invoice using java code.

**Comment by nikunj0123** [comment]
I am able to create Invoice using curl command and using postman client. But not through java code.

**Comment by jaredtking** [comment]
Unfortunately we cannot help you with Java, but you might find help on a forum like [StackOverflow](http://stackoverflow.com/questions/238824/getting-a-file-from-an-http-request-in-java). I'm going to close this issue for now. If you run into any specific errors with the API that we can help with then please let us know. Thank you.
